import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import NavBar from '@/components/NavBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`dark`} >
        <Providers>
   
          <NavBar />
           <main className=' max-w-6xl mx-auto mt-10 mb-3 '>
           {children}
           </main>
        </Providers>
      </body>
    </html>
  )
}
